### PR TITLE
make model search box optional

### PR DESCRIPTION
**Pull request by pderouen**
I will update the docs page with an example of how to turn off the model search feature.  Any recommendation for a test?

### CODE REVIEW

**Review by ginty — CHANGES_REQUESTED** [review]
You need to take out the closing <\article> tag also, otherwise looks good

**Comment by ginty** [comment]
No recommendation for a test, I think its OK without.

This seems to be making the default behavior to have search disabled, which I am OK with, but just wanted to check that's what you intend since you talk about updating the docs with how to turn off search, when really the required change is to document how to turn it on.

**Comment by pderouen** [comment]
No, the default behavior was supposed to be to keep the search box.  Good catch.  When I switched to making the search box boolean an attribute instead of an option that gets propagated, I forgot to also move the option merge statement.

**Comment by pderouen** [comment]
@ginty this should now contain all of my intended updates.

**Review by ginty — APPROVED** [review]
LGTM

I assume this does actually fix your slow web pages?

**Comment by pderouen** [comment]
Yes, it is quite peppy now.

**Pull request merged**
