### PR TITLE
Fix :msb0 register display bug

### PR DESCRIPTION
**Pull request by pderouen**
Updated the logic to match reg.inspect
https://github.com/Origen-SDK/origen/blob/212d9a943fbb5c31e34bb552b7e8f0187871b821/lib/origen/registers/reg.rb#L188-L207

### CODE REVIEW

**Comment by ginty** [comment]
Thanks for fixing this.

It looks like the inspect code has further references to bit_order which are to handle these non-byte aligned cases - https://github.com/Origen-SDK/origen/blob/212d9a943fbb5c31e34bb552b7e8f0187871b821/approved/inspections.txt#L93-L152

Can we also add that here?

**Comment by pderouen** [comment]
Good catch. I didn't think to check for that.

**Review by ginty — APPROVED** [review]
@pderouen, I fixed the border on the non-byte aligned regs, this is good to go from me.

**Comment by pderouen** [comment]
@ginty, thank you!

**Pull request merged**
